import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react';


const defaultEndpoint = 'https://rickandmortyapi.com/api/character/';

export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint);
  const data = await res.json();
  return {
    props: {
      data
    }
  }
}

export default function Home({ data }) {
  const { info, results: defaultResults = [] } = data;
  const [results, updateResults] = useState(defaultResults);
  const [page, updatePage] = useState({
    ...info,
    current: defaultEndpoint
  });
  const { current } = page;

useEffect(() => {
  if ( current === defaultEndpoint ) return;

  async function request() {
    const res = await fetch(current)
    const nextData = await res.json();

    updatePage({
      current,
      ...nextData.info
    });

    if ( !nextData.info?.prev ) {
      updateResults(nextData.results);
      return;
    }

    updateResults(prev => {
      return [
        ...prev,
        ...nextData.results
      ]
    });
  }

  request();
}, [current]);


      function handleLoadMore() {
        updatePage(prev => {
          return {
            ...prev,
            current: page?.next
          }
        });
      }

      function handleOnSubmitSearch(e) {
        e.preventDefault();
      
        const { currentTarget = {} } = e;
        const fields = Array.from(currentTarget?.elements);
        const fieldQuery = fields.find(field => field.name === 'query');
      
        const value = fieldQuery.value || '';
        const endpoint = `https://rickandmortyapi.com/api/character/?name=${value}`;
      
        updatePage({
          current: endpoint
        });
      }

  return (
    <div className={styles.container}>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Rick and Morty
        </h1>

        <p className={styles.description}>
           Ni lo entiendo, ni necesito entenderlo
        </p>

        <form className="search" onSubmit={handleOnSubmitSearch}>
  <input name="query" type="search" />
  <button>Buscar</button>
</form>

        <ul className="grid">
          {results.map(result => {
            const { id, name, image } = result;
            return (
              <li key={id} className="card">
            
                <div className={styles.grid}>
                  <a>
                    <h3>{ name }</h3>
                    <img src={image} alt={`${name} Thumbnail`} width="200" height={200}/>
                  </a>
                </div>
                
              </li>
            )
          })}
        </ul>

        <p>
        <button onClick={handleLoadMore}>Load More</button>
</p>
        
        </main>

      
    </div>
  )
}
